// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqqqqoabmjbbwudcvftt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxcXFxb2FibWpiYnd1ZGN2ZnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjQ3MTMsImV4cCI6MjA2NzU0MDcxM30.GULQCuN5JmKDj5ghoP27fgXP3YDTZgsmW4jRjJb957o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});