// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsrkclxrbdhaeraeobpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzcmtjbHhyYmRoYWVyYWVvYnB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDE4NTksImV4cCI6MjA2NzU3Nzg1OX0.v1OCCBoO5dihSWW8bdL7Gm_aKyxaFKtTLrn4LdNUmnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});